/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IUniStrategyInterface extends ethers.utils.Interface {
  functions: {
    "getReadjustThreshold(address)": FunctionFragment;
    "getTicks(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getReadjustThreshold",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getTicks", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getReadjustThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTicks", data: BytesLike): Result;

  events: {
    "BaseMultiplierUpdated(int24,int24)": EventFragment;
    "MaxTwapDeviationUpdated(int24,int24)": EventFragment;
    "PriceThresholdUpdated(uint24,uint24)": EventFragment;
    "RangeMultiplierUpdated(int24,int24)": EventFragment;
    "StrategyUpdated(tuple,tuple)": EventFragment;
    "SwapPercentageUpdated(uint8,uint8)": EventFragment;
    "TwapDurationUpdated(uint32,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BaseMultiplierUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxTwapDeviationUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceThresholdUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RangeMultiplierUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapPercentageUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwapDurationUpdated"): EventFragment;
}

export class IUniStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IUniStrategyInterface;

  functions: {
    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<[number] & { readjustThreshold: number }>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getReadjustThreshold(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getTicks(
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getTicks(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number, number] & {
        baseLower: number;
        baseUpper: number;
        bidLower: number;
        bidUpper: number;
        askLower: number;
        askUpper: number;
      }
    >;
  };

  filters: {
    BaseMultiplierUpdated(
      oldMultiplier?: null,
      newMultiplier?: null
    ): TypedEventFilter<
      [number, number],
      { oldMultiplier: number; newMultiplier: number }
    >;

    MaxTwapDeviationUpdated(
      oldDeviation?: null,
      newDeviation?: null
    ): TypedEventFilter<
      [number, number],
      { oldDeviation: number; newDeviation: number }
    >;

    PriceThresholdUpdated(
      oldThreshold?: null,
      newThreshold?: null
    ): TypedEventFilter<
      [number, number],
      { oldThreshold: number; newThreshold: number }
    >;

    RangeMultiplierUpdated(
      oldMultiplier?: null,
      newMultiplier?: null
    ): TypedEventFilter<
      [number, number],
      { oldMultiplier: number; newMultiplier: number }
    >;

    StrategyUpdated(
      oldStrategy?: null,
      newStrategy?: null
    ): TypedEventFilter<
      [
        [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        },
        [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        }
      ],
      {
        oldStrategy: [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        };
        newStrategy: [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        };
      }
    >;

    SwapPercentageUpdated(
      oldPercentage?: null,
      newPercentage?: null
    ): TypedEventFilter<
      [number, number],
      { oldPercentage: number; newPercentage: number }
    >;

    TwapDurationUpdated(
      oldDuration?: null,
      newDuration?: null
    ): TypedEventFilter<
      [number, number],
      { oldDuration: number; newDuration: number }
    >;
  };

  estimateGas: {
    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
