/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ULMStateInterface extends ethers.utils.Interface {
  functions: {
    "getPoolDetails(address)": FunctionFragment;
    "getPositionDetails(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getPoolDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionDetails",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPoolDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionDetails",
    data: BytesLike
  ): Result;

  events: {};
}

export class ULMState extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ULMStateInterface;

  functions: {
    getPoolDetails(
      pool: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, number, BigNumber, BigNumber, number] & {
        token0: string;
        token1: string;
        fee: number;
        poolCardinality: number;
        liquidity: BigNumber;
        sqrtPriceX96: BigNumber;
        currentTick: number;
      }
    >;

    getPositionDetails(
      tokenId: BigNumberish,
      liquidityManagerAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        pool: string;
        token0: string;
        token1: string;
        currentTick: number;
        fee: number;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
        totalLiquidity: BigNumber;
      }
    >;
  };

  getPoolDetails(
    pool: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, number, BigNumber, BigNumber, number] & {
      token0: string;
      token1: string;
      fee: number;
      poolCardinality: number;
      liquidity: BigNumber;
      sqrtPriceX96: BigNumber;
      currentTick: number;
    }
  >;

  getPositionDetails(
    tokenId: BigNumberish,
    liquidityManagerAddress: string,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      number,
      number,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      pool: string;
      token0: string;
      token1: string;
      currentTick: number;
      fee: number;
      liquidity: BigNumber;
      amount0: BigNumber;
      amount1: BigNumber;
      totalLiquidity: BigNumber;
    }
  >;

  callStatic: {
    getPoolDetails(
      pool: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, number, BigNumber, BigNumber, number] & {
        token0: string;
        token1: string;
        fee: number;
        poolCardinality: number;
        liquidity: BigNumber;
        sqrtPriceX96: BigNumber;
        currentTick: number;
      }
    >;

    getPositionDetails(
      tokenId: BigNumberish,
      liquidityManagerAddress: string,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        number,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        pool: string;
        token0: string;
        token1: string;
        currentTick: number;
        fee: number;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
        totalLiquidity: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    getPoolDetails(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPositionDetails(
      tokenId: BigNumberish,
      liquidityManagerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPoolDetails(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPositionDetails(
      tokenId: BigNumberish,
      liquidityManagerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
