/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface UniStrategyInterface extends ethers.utils.Interface {
  functions: {
    "baseMultiplier()": FunctionFragment;
    "changeStrategy(tuple,address)": FunctionFragment;
    "getReadjustThreshold(address)": FunctionFragment;
    "getStrategy(address)": FunctionFragment;
    "getTicks(address)": FunctionFragment;
    "getTwap(address)": FunctionFragment;
    "governance()": FunctionFragment;
    "rangeMultiplier()": FunctionFragment;
    "setBaseMutiplier(int24)": FunctionFragment;
    "setMaxTwapDeviation(int24)": FunctionFragment;
    "setRangeMultiplier(int24)": FunctionFragment;
    "setReadjustMultiplier(int24)": FunctionFragment;
    "setTwapDuration(uint32)": FunctionFragment;
    "unipilot()": FunctionFragment;
    "updateUnipilotAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "baseMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeStrategy",
    values: [
      {
        baseThreshold: BigNumberish;
        rangeThreshold: BigNumberish;
        maxTwapDeviation: BigNumberish;
        readjustThreshold: BigNumberish;
        twapDuration: BigNumberish;
      },
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getReadjustThreshold",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getStrategy", values: [string]): string;
  encodeFunctionData(functionFragment: "getTicks", values: [string]): string;
  encodeFunctionData(functionFragment: "getTwap", values: [string]): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rangeMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseMutiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTwapDeviation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRangeMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReadjustMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTwapDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unipilot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateUnipilotAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "baseMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReadjustThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTicks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rangeMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseMutiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTwapDeviation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRangeMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReadjustMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTwapDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unipilot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateUnipilotAddress",
    data: BytesLike
  ): Result;

  events: {
    "BaseMultiplierUpdated(int24,int24)": EventFragment;
    "MaxTwapDeviationUpdated(int24,int24)": EventFragment;
    "PriceThresholdUpdated(uint24,uint24)": EventFragment;
    "RangeMultiplierUpdated(int24,int24)": EventFragment;
    "StrategyUpdated(tuple,tuple)": EventFragment;
    "SwapPercentageUpdated(uint8,uint8)": EventFragment;
    "TwapDurationUpdated(uint32,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BaseMultiplierUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxTwapDeviationUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceThresholdUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RangeMultiplierUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapPercentageUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwapDurationUpdated"): EventFragment;
}

export class UniStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UniStrategyInterface;

  functions: {
    baseMultiplier(overrides?: CallOverrides): Promise<[number]>;

    changeStrategy(
      params: {
        baseThreshold: BigNumberish;
        rangeThreshold: BigNumberish;
        maxTwapDeviation: BigNumberish;
        readjustThreshold: BigNumberish;
        twapDuration: BigNumberish;
      },
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<[number] & { readjustThreshold: number }>;

    getStrategy(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        }
      ] & {
        strategy: [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        };
      }
    >;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTwap(_pool: string, overrides?: CallOverrides): Promise<[number]>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    rangeMultiplier(overrides?: CallOverrides): Promise<[number]>;

    setBaseMutiplier(
      _baseMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRangeMultiplier(
      _rangeMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unipilot(overrides?: CallOverrides): Promise<[string]>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  baseMultiplier(overrides?: CallOverrides): Promise<number>;

  changeStrategy(
    params: {
      baseThreshold: BigNumberish;
      rangeThreshold: BigNumberish;
      maxTwapDeviation: BigNumberish;
      readjustThreshold: BigNumberish;
      twapDuration: BigNumberish;
    },
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getReadjustThreshold(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getStrategy(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number, number, number] & {
      baseThreshold: number;
      rangeThreshold: number;
      maxTwapDeviation: number;
      readjustThreshold: number;
      twapDuration: number;
    }
  >;

  getTicks(
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTwap(_pool: string, overrides?: CallOverrides): Promise<number>;

  governance(overrides?: CallOverrides): Promise<string>;

  rangeMultiplier(overrides?: CallOverrides): Promise<number>;

  setBaseMutiplier(
    _baseMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxTwapDeviation(
    _twapDeviation: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRangeMultiplier(
    _rangeMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setReadjustMultiplier(
    _readjustMultipier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTwapDuration(
    _twapDuration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unipilot(overrides?: CallOverrides): Promise<string>;

  updateUnipilotAddress(
    _unipilot: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    baseMultiplier(overrides?: CallOverrides): Promise<number>;

    changeStrategy(
      params: {
        baseThreshold: BigNumberish;
        rangeThreshold: BigNumberish;
        maxTwapDeviation: BigNumberish;
        readjustThreshold: BigNumberish;
        twapDuration: BigNumberish;
      },
      _pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getStrategy(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number] & {
        baseThreshold: number;
        rangeThreshold: number;
        maxTwapDeviation: number;
        readjustThreshold: number;
        twapDuration: number;
      }
    >;

    getTicks(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number, number] & {
        baseLower: number;
        baseUpper: number;
        bidLower: number;
        bidUpper: number;
        askLower: number;
        askUpper: number;
      }
    >;

    getTwap(_pool: string, overrides?: CallOverrides): Promise<number>;

    governance(overrides?: CallOverrides): Promise<string>;

    rangeMultiplier(overrides?: CallOverrides): Promise<number>;

    setBaseMutiplier(
      _baseMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setRangeMultiplier(
      _rangeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    unipilot(overrides?: CallOverrides): Promise<string>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BaseMultiplierUpdated(
      oldMultiplier?: null,
      newMultiplier?: null
    ): TypedEventFilter<
      [number, number],
      { oldMultiplier: number; newMultiplier: number }
    >;

    MaxTwapDeviationUpdated(
      oldDeviation?: null,
      newDeviation?: null
    ): TypedEventFilter<
      [number, number],
      { oldDeviation: number; newDeviation: number }
    >;

    PriceThresholdUpdated(
      oldThreshold?: null,
      newThreshold?: null
    ): TypedEventFilter<
      [number, number],
      { oldThreshold: number; newThreshold: number }
    >;

    RangeMultiplierUpdated(
      oldMultiplier?: null,
      newMultiplier?: null
    ): TypedEventFilter<
      [number, number],
      { oldMultiplier: number; newMultiplier: number }
    >;

    StrategyUpdated(
      oldStrategy?: null,
      newStrategy?: null
    ): TypedEventFilter<
      [
        [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        },
        [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        }
      ],
      {
        oldStrategy: [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        };
        newStrategy: [number, number, number, number, number] & {
          baseThreshold: number;
          rangeThreshold: number;
          maxTwapDeviation: number;
          readjustThreshold: number;
          twapDuration: number;
        };
      }
    >;

    SwapPercentageUpdated(
      oldPercentage?: null,
      newPercentage?: null
    ): TypedEventFilter<
      [number, number],
      { oldPercentage: number; newPercentage: number }
    >;

    TwapDurationUpdated(
      oldDuration?: null,
      newDuration?: null
    ): TypedEventFilter<
      [number, number],
      { oldDuration: number; newDuration: number }
    >;
  };

  estimateGas: {
    baseMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    changeStrategy(
      params: {
        baseThreshold: BigNumberish;
        rangeThreshold: BigNumberish;
        maxTwapDeviation: BigNumberish;
        readjustThreshold: BigNumberish;
        twapDuration: BigNumberish;
      },
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStrategy(_pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTwap(_pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    rangeMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    setBaseMutiplier(
      _baseMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRangeMultiplier(
      _rangeMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unipilot(overrides?: CallOverrides): Promise<BigNumber>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    baseMultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeStrategy(
      params: {
        baseThreshold: BigNumberish;
        rangeThreshold: BigNumberish;
        maxTwapDeviation: BigNumberish;
        readjustThreshold: BigNumberish;
        twapDuration: BigNumberish;
      },
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStrategy(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTwap(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rangeMultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBaseMutiplier(
      _baseMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRangeMultiplier(
      _rangeMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unipilot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
